sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm run test

after_success:
  - docker build -t martimlinux/multi-client ./client
  - docker build -t martimlinux/multi-nginx ./nginx
  - docker build -t martimlinux/multi-api ./server
  - docker build -t martimlinux/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push martimlinux/multi-client
  - docker push martimlinux/multi-nginx
  - docker push martimlinux/multi-api
  - docker push martimlinux/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "multi-docker-1  "
  env: "MultiDocker-env-1"
  bucket_name: "elasticbeanstalk-eu-west-3-173841254803"
  bucket_path: "docker-aws"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"